services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  ServerKnights\SkNewsletterhelper\:
    resource: '../Classes/*'

  # Content Object for newsletter Plugins
  ServerKnights\SkNewsletterhelper\ContentObject\NewsletterCoreContentObject:
    tags:
      - name: frontend.contentobject
        identifier: 'NEWSLETTERCORE'

  ServerKnights\SkNewsletterhelper\Controller\BackendModuleController:
    public: true

  ServerKnights\SkNewsletterhelper\Service\ExtentionConfigurationService:
    public: true

  ServerKnights\SkNewsletterhelper\Controller\NewsletterHelperController:
    public: true
    tags: [ 'frontend.controller' ]